# Generated by Django 3.2.25 on 2026-09-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
